---
development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292

prodution:
  API_URL: https://cgroup2-api.herokuapp.com/api/v1
  APP_URL: https://cgroup2-app.herokuapp.com/

